---
include:
  # Wireless dongle - Arduino Nano 33 BLE as central with ZMK Studio
  - board: arduino_nano_33_ble
    shield: eyelash_corne_dongle
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: eyelash_corne_dongle_studio

  # Right peripheral - connects wirelessly to dongle
  - board: eyelash_nano
    shield: eyelash_corne_right nice_oled
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

  # Left peripheral - connects wirelessly to dongle
  - board: eyelash_nano
    shield: eyelash_corne_left nice_oled
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

  # Settings reset for dongle
  - board: arduino_nano_33_ble
    shield: settings_reset

  # Settings reset for keyboard halves
  - board: eyelash_nano
    shield: settings_reset
 
